version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'

  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: holded123
      MYSQL_DATABASE: holded_events
      MYSQL_USER: holded
      MYSQL_PASSWORD: holded123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    hostname: api
    container_name: holded-api
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - mysql
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: holded_events
      MYSQL_USER: holded
      MYSQL_PASSWORD: holded123
    volumes:
      - ./api:/app
    command: poetry run python main.py

  beam-pipeline:
    build:
      context: ./beam
      dockerfile: Dockerfile
    hostname: beam-pipeline
    container_name: holded-beam
    depends_on:
      - kafka
      - mysql
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: holded_events
      MYSQL_USER: holded
      MYSQL_PASSWORD: holded123
    volumes:
      - ./beam:/app
    command: poetry run python pipeline.py

volumes:
  mysql_data:
